name: my-flask-clustering-app
channels:
  - conda-forge
dependencies:
  - python=3.9
  - flask=2.0.1
  - werkzeug<2.1
  - numpy=1.22.0
  - scikit-learn=1.0.2
  - umap-learn=0.5.3
  - hdbscan=0.8.29
  - pandas=1.4.0
  - gunicorn=20.1.0
  - flask-cors=3.0.10
  - scikit-learn=1.0.2